In [47]:
import pandas as pd

In [48]:
# df=pd.read_csv("DataSets\Melbourne_housing_FULL.csv")

In [49]:
# df

In [50]:
# df.info()

In [51]:
# df.describe()

In [52]:
# import numpy as np
# a1=np.arange(0,9,1)

# a=a1.reshape(3,3)
# print(a)

In [53]:
# try :
#     num=int(input("Enter a Number:"))
#     res=10/num
#     print(res)
# except ValueError:
#     print('Please Enter a correct value')

# except ZeroDivisionError:
#     print("Number cant be divided by zero")
# finally:
#     print("DOne")

In [54]:
filename=open("p1.txt","a")
filename.write("I am good")
filename.close()

In [55]:
filename=open("p1.txt","a")
filename.write("How are you?")
print(filename)
filename.close()


<_io.TextIOWrapper name='p1.txt' mode='a' encoding='cp1252'>


In [56]:
with open("p1.txt","a") as file:
    file.write("Our best year ever\n")
    file.write("we show up better")


In [57]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.median(arr, axis=0))

[2.5 3.5 4.5]


In [58]:
import  os
if os.path.exists('P1.py'):
    print("Path exists")
else:
    print("Path doesnot exists")

Path exists


In [59]:
b1=np.linspace(1,5,5)
print(b1.var())

2.0


In [60]:
v1 = np.array([[1, 3, 45],
               [2, 4, 5]])

v2 = np.array([[6, 8, 2],
               [8, 5, 4]])

v3=np.cross(v1,v2)
print(v3)

[[-354  268  -10]
 [  -9   32  -22]]


In [61]:
A=np.array([[2,0],[0,4]])
evalue,evectors1=np.linalg.eig(A)
print(evalue)
print(evectors1)

[2. 4.]
[[1. 0.]
 [0. 1.]]


In [62]:
arr4=np.array([1, 2, 3])
arr5=np.array([7, 8, 9])
res=arr4*arr5
res1=np.dot(arr4,arr5)
# res2=np.matmul(arr4,arr5)
# print(res)
print(res1)


50


In [63]:
from scipy import stats

arr6 = [12,65,5,45,41,21,15,121,21,211,2,1215,12,2,14,12,1,51,21,1,51,4,14,5,5,15]
print(stats.mode(arr6))

ModeResult(mode=np.int64(5), count=np.int64(3))
